app:
  port: 3000

mongodb:
  uri: 'mongodb://cryptometric:cryptometric@localhost:27017/cryptometrics'
  dbName: cryptometrics

auth:
  secret: adkgfn274ot41%$&/%3215

logger:
  level: trace

crypto:
  secretKey: $%&456536#$%&GDSegw

coinmarketcap:
  apiKey: 705e85d2-f70f-4525-8b13-108567b2d5c5