app:
  port: PORT

mongodb:
  uri: MONGODB_URI
  dbName: MONGODB_NAME

connectorManager:
  kucoin:
    environment: live

redis:
  endpoint: <uri>

auth:
  secret: <sessionSecret>
  duration: <sessionDuration

logger:
  level: trace

crypto:
  secretKey: <apiKeyEncription>

coinmarketcap:
  apiKey: <coinmarketcap>
  limit: 5000

scheduler:
  time: 86400000