openapi: 3.0.0
info: 
  title: CryptoMetrics API
  version: 0.0.1
  description: An app to view all the metrics of your cryptowallet
servers:
- url: http://localhost:3000/api/v1
  description: The development API server
paths:
  /login:
    $ref: ./login.yaml#/login
  /logout:
    $ref: ./logout.yaml#/logout
  /users:
    $ref: ./user.yaml#/collection
  /users/{id}:
    $ref: ./user.yaml#/instance
  /users/{id}/wallet:
    $ref: ./wallet.yaml#/collection
  /users/{id}/apiKey:
    $ref: ./apiKey.yaml#/collection
  /users/{id}/apiKey/{apiKey}:
    $ref: ./apiKey.yaml#/instance


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []