openapi: 3.0.0
info: 
  title: CryptoMetrics API
  version: 0.0.1
  description: An app to view all the metrics of your cryptowallet
servers:
- url: http://localhost:3000/api/v1
  description: The development API server
paths:
  /login:
    $ref: ./login.yaml#/login
  /logout:
    $ref: ./logout.yaml#/logout
  /users:
    $ref: ./user.yaml#/collection
  /users/{id}:
    $ref: ./user.yaml#/instance
  /users/{id}/staticCrypto:
    $ref: ./staticCrypto.yaml#/collection
  /users/{id}/staticCrypto/{crypto}:
    $ref: ./staticCrypto.yaml#/instance
  /users/{id}/wallet:
    $ref: ./wallet.yaml#/collection
  /users/{id}/apiKey:
    $ref: ./apiKey.yaml#/collection
  /users/{id}/apiKey/{apiKey}:
    $ref: ./apiKey.yaml#/instance
  /users/{id}/apiKey/{apiKey}/enable:
    $ref: ./apiKey.yaml#/enable
  /users/{id}/apiKey/{apiKey}/disable:
    $ref: ./apiKey.yaml#/disable


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-access-token

security:
  - ApiKeyAuth: []